apiVersion: skaffold/v4beta6
kind: Config
manifests:
  rawYaml:
    - './infra/k8s/ingress-srv.yaml'
    - './infra/k8s/leaderboard-depl.yaml'
    - './infra/k8s/leaderboard-mongo-depl.yaml'
    - './infra/k8s/client-depl.yaml'
build:
  local:
    push: false
  artifacts:
    - image: amansinghs/catcher-leaderboard
      context: leaderboard
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: amansinghs/catcher-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
