name: tests-leaderboard

on:
  pull_request:
    paths:
      - 'leaderboard/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd leaderboard && npm install && npm run test:ci
